# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  secret_key_base: 4a80950b0cd51031beb7cd73dc1bb6b7089cca9350d5920d777eb1eacdacfee33caf0d053c5773a529e48a1192f3078db25c1ae558e11a1e06c1b90cdd961b62
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: f261601a9e8aa3b04a6a19b1193b8fac78a930dfabe10b8213b752c6ea53cd7d733fdd4f745e515caa8519d125042ff4e48df8962458f5d92869592ee8ece4f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
